# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=6)),
                ('cover', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentlyReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currently_reading', to='blog.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('intro', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookReviewPostContent',
            fields=[
                ('postcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.PostContent')),
                ('rating', models.SmallIntegerField()),
                ('text', models.TextField()),
                ('align', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='blog.Book')),
            ],
            options={
                'verbose_name': 'Book review (content)',
                'verbose_name_plural': 'Book reviews (content)',
            },
            bases=('blog.postcontent',),
        ),
        migrations.CreateModel(
            name='TextPostContent',
            fields=[
                ('postcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.PostContent')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text (content)',
                'verbose_name_plural': 'Texts (content)',
            },
            bases=('blog.postcontent',),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blog.Post'),
        ),
    ]
