# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
